version: '2'
volumes:
    slave-m2-repository:
services:
    gerrit:
        build:
            context: gerrit/
            args:
                - http_proxy
                - https_proxy
                - no_proxy
        expose:
            - "8080"
            - "29418"
        ports:
            - "29418:29418"
        environment:
            # http
            "PROXY_URL":

            # ldap
            "LDAP_URL":
            "LDAP_ACCOUNT_BASE":
            "LDAP_GROUP_BASE":

            # smtp
            "SMTP_SERVER":
            "SMTP_SERVER_PORT":
            "SMTP_FROM":

            # jira
            "JIRA_URL":
        volumes:
            - ./data/gerrit-volume:/home/gerrit/review_site
            # timezone
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
    nexus:
        build:
            context: nexus/
            args:
                - http_proxy
                - https_proxy
                - no_proxy
        expose:
            # www
            - "8081"
            # docker registry
            - "5000"
        volumes:
            - ./data/nexus-volume:/opt/sonatype/nexus/data
            # timezone
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
    jenkins:
        build:
            context: jenkins/
            args:
                - http_proxy
                - https_proxy
                - no_proxy
        expose:
            - "8080"
        # for slaves
        ports:
            - "50000:50000"
        volumes:
            - ./data/jenkins-volume:/var/jenkins_home
            # See: https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
            - /var/run/docker.sock:/run/docker.sock
            # timezone
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            JAVA_OPTS: "-Djava.awt.headless=true"
    proxy:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
            - "5000:5000"
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf.template:ro
            - ./data/proxy-volume/certificates:/etc/nginx/certificates
            # timezone
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            - SSL_CERTIFICATE_NAME
        command: /bin/bash -c "envsubst '$${SSL_CERTIFICATE_NAME}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.179.0.0/16

