gerrit:
    build: gerrit/
    expose:
        - "8080"
    environment:
        PROXY_HOST: "localhost"
    volumes:
        - ./data/gerrit-volume:/home/gerrit/review_site
proxy:
    image: nginx
    ports:
        - "80:80"
    links:
        - gerrit
    volumes:
        - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro

