version: '2'
services:
    gerrit:
        build:
            context: gerrit/
            args:
                - http_proxy
                - https_proxy
                - no_proxy
        expose:
            - "8080"
            - "29418"
        environment:
            # http
            "PROXY_URL":

            # ldap
            "LDAP_URL":
            "LDAP_ACCOUNT_BASE":
            "LDAP_GROUP_BASE":

            # smtp
            "SMTP_SERVER":
            "SMTP_SERVER_PORT":
            "SMTP_FROM":

            # jira
            "JIRA_URL":
        volumes:
            - ./data/gerrit-volume:/home/gerrit/review_site
    nexus:
        build:
            context: nexus/
            args:
                - http_proxy
                - https_proxy
                - no_proxy
        expose:
            - "8081"
        volumes:
             - ./data/nexus-volume:/opt/sonatype/nexus/data
    jenkins:
        build:
            context: jenkins/
            args:
                - http_proxy
                - https_proxy
                - no_proxy
        expose:
            - "8080"
        volumes:
            - ./data/jenkins-volume:/var/jenkins_home
            - /var/run/docker.sock:/run/docker.sock
        environment:
            JAVA_OPTS: "-Djava.awt.headless=true"
        #    go-server:
        #        build:
        #            context: go-server
        #            args:
        #                - http_proxy
        #                - https_proxy
        #                - no_proxy
        #        expose:
        #            - "8153"
        #        volumes:
        #            - ./data/goserver-volume/data:/var/lib/go-server
        #            - ./data/goserver-volume/log:/var/log/go-server
        #            - ./data/goserver-volume/etc:/etc/go
        #            - ./data/goserver-volume/addons:/go-addons
        #            - ./data/goserver-volume/home:/var/go
        #    go-agent1:
        #        build:
        #            context: go-agent
        #            args:
        #                - http_proxy
        #                - https_proxy
        #                - no_proxy
        #    go-agent2:
        #        build:
        #            context: go-agent
        #            args:
        #                - http_proxy
        #                - https_proxy
        #                - no_proxy
    proxy:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
